import java.io.Serializable;
import java.util.Date;

/**
 * Model class of alquiler.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Alquiler implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** inicio. */
	private Date inicio;

	/** fin. */
	private Date fin;

	/** usuarios. */
	private Usuarios usuarios;

	/** vehiculos. */
	private Vehiculos vehiculos;

	/**
	 * Constructor.
	 */
	public Alquiler() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the inicio.
	 * 
	 * @param inicio
	 *            inicio
	 */
	public void setInicio(Date inicio) {
		this.inicio = inicio;
	}

	/**
	 * Get the inicio.
	 * 
	 * @return inicio
	 */
	public Date getInicio() {
		return this.inicio;
	}

	/**
	 * Set the fin.
	 * 
	 * @param fin
	 *            fin
	 */
	public void setFin(Date fin) {
		this.fin = fin;
	}

	/**
	 * Get the fin.
	 * 
	 * @return fin
	 */
	public Date getFin() {
		return this.fin;
	}

	/**
	 * Set the usuarios.
	 * 
	 * @param usuarios
	 *            usuarios
	 */
	public void setusuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	/**
	 * Get the usuarios.
	 * 
	 * @return usuarios
	 */
	public Usuarios getusuarios() {
		return this.usuarios;
	}

	/**
	 * Set the vehiculos.
	 * 
	 * @param vehiculos
	 *            vehiculos
	 */
	public void setvehiculos(Vehiculos vehiculos) {
		this.vehiculos = vehiculos;
	}

	/**
	 * Get the vehiculos.
	 * 
	 * @return vehiculos
	 */
	public Vehiculos getvehiculos() {
		return this.vehiculos;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Alquiler other = (Alquiler) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
