import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of usuarios.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Usuarios implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** nombre. */
	private String nombre;

	/** dni. */
	private String dni;

	/** The set of alquiler. */
	private Set<Alquiler> alquilerSet;

	/**
	 * Constructor.
	 */
	public Usuarios() {
		this.alquilerSet = new HashSet<Alquiler>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the nombre.
	 * 
	 * @param nombre
	 *            nombre
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * Get the nombre.
	 * 
	 * @return nombre
	 */
	public String getNombre() {
		return this.nombre;
	}

	/**
	 * Set the dni.
	 * 
	 * @param dni
	 *            dni
	 */
	public void setDni(String dni) {
		this.dni = dni;
	}

	/**
	 * Get the dni.
	 * 
	 * @return dni
	 */
	public String getDni() {
		return this.dni;
	}

	/**
	 * Set the set of the alquiler.
	 * 
	 * @param alquilerSet
	 *            The set of alquiler
	 */
	public void setAlquilerSet(Set<Alquiler> alquilerSet) {
		this.alquilerSet = alquilerSet;
	}

	/**
	 * Add the alquiler.
	 * 
	 * @param alquiler
	 *            alquiler
	 */
	public void addAlquiler(Alquiler alquiler) {
		this.alquilerSet.add(alquiler);
	}

	/**
	 * Get the set of the alquiler.
	 * 
	 * @return The set of alquiler
	 */
	public Set<Alquiler> getAlquilerSet() {
		return this.alquilerSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Usuarios other = (Usuarios) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
