import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of vehiculos.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Vehiculos implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** marca. */
	private String marca;

	/** modelo. */
	private String modelo;

	/** tipo. */
	private Object tipo;

	/** The set of alquiler. */
	private Set<Alquiler> alquilerSet;

	/**
	 * Constructor.
	 */
	public Vehiculos() {
		this.alquilerSet = new HashSet<Alquiler>();
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the marca.
	 * 
	 * @param marca
	 *            marca
	 */
	public void setMarca(String marca) {
		this.marca = marca;
	}

	/**
	 * Get the marca.
	 * 
	 * @return marca
	 */
	public String getMarca() {
		return this.marca;
	}

	/**
	 * Set the modelo.
	 * 
	 * @param modelo
	 *            modelo
	 */
	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	/**
	 * Get the modelo.
	 * 
	 * @return modelo
	 */
	public String getModelo() {
		return this.modelo;
	}

	/**
	 * Set the tipo.
	 * 
	 * @param tipo
	 *            tipo
	 */
	public void setTipo(Object tipo) {
		this.tipo = tipo;
	}

	/**
	 * Get the tipo.
	 * 
	 * @return tipo
	 */
	public Object getTipo() {
		return this.tipo;
	}

	/**
	 * Set the set of the alquiler.
	 * 
	 * @param alquilerSet
	 *            The set of alquiler
	 */
	public void setAlquilerSet(Set<Alquiler> alquilerSet) {
		this.alquilerSet = alquilerSet;
	}

	/**
	 * Add the alquiler.
	 * 
	 * @param alquiler
	 *            alquiler
	 */
	public void addAlquiler(Alquiler alquiler) {
		this.alquilerSet.add(alquiler);
	}

	/**
	 * Get the set of the alquiler.
	 * 
	 * @return The set of alquiler
	 */
	public Set<Alquiler> getAlquilerSet() {
		return this.alquilerSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Vehiculos other = (Vehiculos) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
